# Generated by Django 6.0.2 on 2026-03-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100)),
                ('course_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('duration', models.IntegerField()),
                ('seat', models.IntegerField()),
            ],
        ),
    ]
