# Generated by Django 6.0.2 on 2026-02-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_adress',
            new_name='student_address',
        ),
    ]
