# Generated by Django 6.0.2 on 2026-02-18 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0002_rename_student_adress_student_student_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentmarks', to='opt.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opt.subject')),
            ],
            options={
                'unique_together': {('student', 'subject')},
            },
        ),
    ]
