# Generated by Django 6.0.2 on 2026-02-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opt', '0003_subject_subjectmark'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject']},
        ),
    ]
