# Generated by Django 4.2.11 on 2026-02-02 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='agree',
            field=models.BooleanField(default=False),
        ),
    ]
