# Generated by Django 6.0.2 on 2026-02-06 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_info_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='agree',
        ),
        migrations.RemoveField(
            model_name='info',
            name='city',
        ),
        migrations.RemoveField(
            model_name='info',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='info',
            name='state',
        ),
        migrations.RemoveField(
            model_name='info',
            name='uName',
        ),
        migrations.RemoveField(
            model_name='info',
            name='zipCode',
        ),
        migrations.AddField(
            model_name='info',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='info',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
